project:
  type: website
  output-dir: docs

website:
  title: "chung-jiwoong.github.io"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Vita
        href: cv.qmd
      - teaching.qmd
      - research.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



