project:
  type: website
  output-dir: docs

website:
  title: "Ji-Woong Chung"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: CV
        href: cv.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Research
        href: research.qmd
# Created this website following the instruction at https://colab.research.google.com/github/jfrench/DataWrangleViz/blob/master/github-website-creation.ipynb
# and this as well: https://ucsb-meds.github.io/creating-quarto-websites/
format:
    html:
      theme: cosmos
      toc: true
