project:
  type: website
  output-dir: docs

website:
  title: "chung-jiwoong.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



