project:
  type: website
  output-dir: docs

website:
  title: "chung-jiwoong.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: Vita
      - href: teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



