project:
  type: website
  output-dir: docs

website:
  title: "Ji-Woong Chung"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Vita
        href: cv.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Research
        href: research.qmd
# Created this website following the instruction at https://colab.research.google.com/github/jfrench/DataWrangleViz/blob/master/github-website-creation.ipynb

format:
    html:
      theme: cosmos
      toc: true
