---
format: 
  html: 
    default: true
    css: styles.css
  typst: default
pagetitle: "CV"
fontsize: 11pt
toc: false
# https://www.yamllint.com/
---

# Ji-Woong Chung
Professor of Finance, Korea University Business School  
[chung_jiwoong@korea.ac.kr](mailto:chung_jiwoong@korea.ac.kr) | [chung-jiwoong.github.io](https://chung-jiwoong.github.io)  
145 Anam-ro, Seongbuk-gu, Seoul, 02841, South Korea | Office: +82-2-3290-2825  


---


## **Employment**
**Korea University Business School**  
Professor, *Mar 2021 – Present*  
Finance Area Chair, *Sep 2023 – Feb 2026*  
Associate Professor, *Mar 2016 – Feb 2021*  
Academic Director, Finance MBA Program, *Mar 2017 – Dec 2018*  
Assistant Professor, *Sep 2012 – Feb 2016*  

**The Chinese University of Hong Kong**  
Assistant Professor, *Aug 2010 – Aug 2012*

---

## **Visiting Positions**

Hong Kong Polytechnic University, *Jul 2020 – Feb 2021*  
Emory University, *Sep 2019 – Dec 2019*  
University of Sydney, *Feb 2017*  

---

## **Education**
**The Ohio State University** – Ph.D. in Finance, *2010*  
**Yonsei University** – B.A. in Economics and Applied Statistics, *2003*  


---

## **Research Papers**

**Published Papers**

- **"The Introduction of Governance Regulation on Financial Institutions and Its Effect on Firm Value"**, with Yangsoo Lee and Koren Jo, *Financial Stability Studies*, 2024
- **"Do Prime Brokers Matter in the Search for Informed Hedge Fund Managers?"**, with George Aragon and Byoung-Uk Kang, *Management Science*, 2023
- **"Has the Value of Cash Increased over Time?"**, with Boochun Jung and Duri Park, *Accounting and Finance*, 2020
- **"Capital Structure and Unemployment Risk: Evidence from Korea"**, with Jaeouk Kim, *Asian Review of Financial Research*, 2017
- **"Prime Broker-Level Comovement in Hedge Fund Returns: Information or Contagion?"**, with Byoung-Uk Kang, *Review of Financial Studies*, 2016
- **"Pay for Performance from Future Fund Flows: The Case of Private Equity"**, with Berk Sensoy, Lea Stern, and Mike Weisbach, *Review of Financial Studies*, 2012

**Working Papers**

- **"Post-Exit Effects of Private Equity Buyouts on Firm Outcomes"**, with Songhee Kim and Koren Jo, 2026
- **"Intended Consequences of More Frequent Portfolio Disclosure of Mutual Funds?"**, with Koren Jo, Jaeouk Kim, and Sejin Kang, 2024
- **"Heterogeneity and Persistence in Performance of Portfolio Managers"**, with Kyeongbae Kim and Jaemin Lee, 2021
- **"Performance Persistence in Private Equity Funds"**, 2012
- **"Leveraged Buyouts of Private Companies"**, 2011

---


## **Book Chapters**

- **"Waterfall in Private Equity"**, in *The Palgrave Encyclopedia of Private Equity*, Springer (eds. Benjamin Hammer and Douglas Cumming)
- **"Compensation Structure"**, Chapter 20 in *Private Equity: Opportunities and Risks*, Oxford University Press (eds. Kent Baker, Halil Kiymaz, and Greg Filbeck)


---

## **Professional Services**

**Associate Editor**  

*International Review of Finance* (*2023 – Present*)  
*Journal of Financial Regulation and Supervision 금융감독연구* (*2023 – Present*)  
*Korean Journal of Financial Studies 재무연구* (*2017 – 2022*)  
*Financial Stability Studies 금융안정연구* (*2015 – 2019*)  
*Korean Journal of Financial Management 재무관리연구* (*2015 – 2016*)  

**Ad-hoc Referee**  

*Asian-Pacific Journal of Financial Studies; Asian Review of Financial Research; Borsa Istanbul Review; Financial Review; Financial Stability Studies; Journal of Banking and Finance; Journal of Business Research; Journal of Finance; Journal of Law, Finance, and Accounting; Journal of Money and Finance; Journal of Risk and Insurance; KDI Journal of Economic Policy; KERI Research Reports; Korea Business Review; Korean Journal of Finance; Korean Journal of Financial Management; Korean Journal of Futures and Options; Korean Management Journal; Korean Management Review; Management Science; Pacific-Basin Finance Journal; Research in International Business and Finance; Review of Financial Studies; Seoul Journal of Business; Venture Review; Yonsei Business Review*  




**Program Committee**

*The Conference on Asia-Pacific Financial Markets (2017 – 2026); Asian Finance Association, Tokyo (2018); Asian Finance Association, Seoul (2017); FMA Asia/Pacific Conference, Taipei (2017); FMA Asia Conference, Seoul (2015)*

**Others**

Director of the Korea Finance Association, *2022 – Present*   
Executive board member of the Korea-America Finance Association, *2017 – 2020*


---

## **Research Presentations**

- **2024:** Conference on Asia-Pacific Financial Markets; Financial Information Society of Korea; Korea-Japan Finance Workshop; Korean Academic Society of Business Administration
- **2023:** Sungkyunkwan University; Korea University
- **2021:** AAA Annual Meetings; Korean Securities Association; AFA Annual Meetings, Chicago
- **2020:** Hanyang University; Korea University
- **2019:** Fordham University; Georgia Institute of Technology; FMA Annual Meetings, New Orleans; University of South Carolina; 11th Annual Hedge Fund and Private Equity Fund Research Conference, Paris
- **2018:** Yonsei University; Seoul National University; SKK Business School; Hong Kong Polytechnic University; Korea Money & Finance Association Meetings; Korea University; Chinese University of Hong Kong
- **2017:** Hanyang University ERICA; University of New South Wales; University of Sydney
- **2016:** FMA–KAFA Session, Las Vegas; Korea Institute of Finance
- **2015:** SKK Business School; Sungkyunkwan University; Korea University; Hanyang University; KAIST; Seoul National University
- **2014:** Ninth International Conference on Asia-Pacific Financial Markets; EFA Annual Meetings, Lugano; China International Conference in Finance, Chengdu; Asian Finance Association Conference, Bali; UNIST; SKK Graduate School of Business; Korea University
- **2013:** Soongsil University; KAIST; Seoul National University
- **2012:** AAA Annual Meetings, Washington DC
- **2011:** Sixth International Conference on Asia-Pacific Financial Markets; Yonsei University; Hong Kong Polytechnic University; Hong Kong Venture Capital and Private Equity Association (HKVCA); EFA Annual Meetings, Stockholm; Fifth Singapore International Conference on Finance; EFM Symposium – Alternative Investment, York University; University of Hong Kong
- **2010:** 3rd Shanghai Winter Finance Conference; Coller Institute of Private Equity at LBS; Chulalongkorn Accounting and Finance Symposium, Bangkok; KAIST; University of Oxford; ESSEC; University of Zurich; City University of Hong Kong; University of Hong Kong; Chinese University of Hong Kong; Korea University; University of Georgia; University of Exeter
- **2009:** FMA Doctoral Consortium, Reno; Ohio State University

---

## **Discussions/Session Chair**

- **2025:** Conference on Asia-Pacific Financial Markets
- **2024:** Korean Academic Society of Business Administration
- **2023:** Conference on Asia-Pacific Financial Markets
- **2021:** China Accounting and Finance Review Annual Meeting
- **2020:** Conference on Asia-Pacific Financial Markets; Asia-Pacific Association of Derivatives
- **2019:** FMA Annual Meetings, New Orleans
- **2018:** Thirteenth International Conference on Asia-Pacific Financial Markets; Korea Securities Association Seminar Series
- **2016:** Eleventh International Conference on Asia-Pacific Financial Markets
- **2015:** Joint Conference of Korean Finance Association and National Pension Research Institute; FMA Asian Meeting
- **2014:** Ninth International Conference on Asia-Pacific Financial Markets; Korean Finance Association Meetings
- **2013:** Eighth International Conference on Asia-Pacific Financial Markets; International Conference on Corporate Governance, Indian School of Business; Korean Finance Association Meetings
- **2012:** Seventh International Conference on Asia-Pacific Financial Markets
- **2011:** Sixth International Conference on Asia-Pacific Financial Markets; EFM Symposium – Alternative Investment, York University


<!-- ## Other Presentations/Discussions 
국회입법조사처, April 2025; [딜사이트 M&A 포럼](https://dealsite.co.kr/articles/132256), November 2024;  Hong Kong Venture Capital and Private Equity Association (HKVCA), August 2011

## External consulting/evaluations
국민연금, 사학연금, 산업통상부, IBK기업은행, 산업은행, 한국산업기술보호협회, 한국에너지기술평가원, 한국에너지경제연구원
-->

---

## **Awards & Grants**

- SK Distinguished Research Award, Korea University Business School (2012, 2016, 2022)
- KU-Future Research Grant (2016, 2017, 2019, 2020)
- INSUNG Research Award (2018)
- LINC Plus Research Grant – *ETF Portfolio Creation* (2017–2018)
- Asian Review of Financial Research Best Paper Award Runner-Up (2017)
- Financial News & KAFA Top-Journal Award (2016)
- General Research Fund, Research Grants Council of Hong Kong (2011/2012, 2012/2013)
- Korea Investment & Securities Outstanding Paper (2011)
- Wharton School WRDS Award for Best Empirical Finance Paper (2011)
- Best Paper Award, Coller Institute of Private Equity at London Business School (2010)

---

## **Expert Witnesses & Legal Opinions**
*Valuation of a call option on an exchangeable bond (2024); Evaluating the impact of dividend payment error on stock price (2020); Valuation of an asset management company (2015); Pricing call options in a related party transaction (2014)*

<!--
Valuation of call option on exchangeable bonds (2024)   
Evaluating the impact of Samsung’s dividend payment error (2020)   
Valuation of Samsung Asset Management  (2015)   
Pricing call options in a related party transaction  (2014)     
-->

---

## **Teaching**
**Undergraduate:** Financial Management, Corporate Finance, Investments, International Financial Management, Management of Financial Institutions, Derivatives  
**MBA:** Alternative Investments, Financial Management, International Financial Management  
**Ph.D.:** Causal Inference in Financial Research, Asset Management, Corporate Finance Theory, Empirical Methods in Finance

---

## **Advisees**  
**Guo Lin** (Assistant Professor, Southwestern University of Finance and Economics)  
**Jaeouk Kim** (Research Fellow, NH Economic Research Institute)  
**Hyunji Lee** (Ph.D. Student, University of Wisconsin-Milwaukee)  
**Jaemin Lee** (Assistant Professor, Chinese University of Hong Kong Shenzhen)  
**Jinyoung Kim** (Research Fellow, Korea Capital Market Institute)  
**Jaeyeon Lee** (Research Fellow, Korea Capital Market Institute)  
**Thomas Seunghyun Lee** (Independent Researcher, Texas Education Agency)  
**Sejin Kang** (Assistant Professor, San Diego State University  

